[project]
id = "fgwtptriileytmmotevs"
name = "Call Lana"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
port = 54323

[functions.create-checkout-session]
verify_jwt = true

[functions.create-payment-method]
verify_jwt = true

[functions.encrypt-secret]
verify_jwt = true

[functions.send-daily-digest]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = true

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false
